services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - airflow-network
    ports:
      - "5432:5432"

  airflow-init:
    image: apache/airflow:2.7.1
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: GeUKtohajvbQgomqORLNTgTSX_J0angtTT3Kmzryv30= # YOUR_SECRET_KEY_HERE
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    networks:
      - airflow-network
    depends_on:
      - postgres
    entrypoint: |
      /bin/bash -c "
      airflow db init &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com
      "

  airflow-webserver:
    image: apache/airflow:2.7.1
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: GeUKtohajvbQgomqORLNTgTSX_J0angtTT3Kmzryv30= # YOUR_SECRET_KEY_HERE
    networks:
      - airflow-network
    depends_on:
      - postgres
      - airflow-init
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    entrypoint: airflow webserver

  airflow-scheduler:
    image: apache/airflow:2.7.1
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: GeUKtohajvbQgomqORLNTgTSX_J0angtTT3Kmzryv30= # YOUR_SECRET_KEY_HERE
    networks:
      - airflow-network
    depends_on:
      - postgres
      - airflow-init
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    entrypoint: airflow scheduler

  data-source-postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: retail_db
    volumes:
      - data-source-db-volume:/var/lib/postgresql/data
    networks:
      - airflow-network
    ports:
      - "5433:5432"

volumes:
  postgres-db-volume:
  data-source-db-volume:

networks:
  airflow-network:
